dems/urls.py
from django.contrib import admin
from django.urls import include, path
from django.utils.translation import ugettext_lazy as _

urlpatterns = [
    path("admin/", admin.site.urls),
    path("markdownx/", include("markdownx.urls")),
    path("", include(("web.urls", "web"), namespace="web")),
]


admin.site.site_header = _("DEMS Admin")
admin.site.site_title = _("DEMS Admin")
admin.site.index_title = _("Welcome to the Digital Exam Management System")

web/urls.py
from django.urls import path

from web.views.dashboard import StudentClassroomsView, StudentDashboardView, StudentExamsView
from web.views.exam import ExamHomeView, QuestionArtifactDownloadView, QuestionEvaluationView, QuestionView
from web.views.main import HomepageView, LoginView, logout_view

urlpatterns = [
    path("", HomepageView.as_view(), name="homepage"),
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", logout_view, name="logout"),
    path("dash/classrooms/", StudentClassroomsView.as_view(), name="classrooms"),
    path(
        "dash/exams/<int:exam_id>/<int:question_id>/evaluate/",
        QuestionEvaluationView.as_view(),
        name="question_evaluation_ajax",
    ),
    path("dash/exams/<int:exam_id>/<int:question_id>/", QuestionView.as_view(), name="question_page"),
    path("dash/exams/<int:exam_id>/", ExamHomeView.as_view(), name="exam_page"),
    path("dash/exams/", StudentExamsView.as_view(), name="exams_dashboard"),
    path("dash/", StudentDashboardView.as_view(), name="student_dashboard"),
    path(
        "download/<int:question_id>/<uuid:artifact_uuid>/",
        QuestionArtifactDownloadView.as_view(),
        name="artifact_download",
    ),
]

classroom/models.py
from django.db import models
from django.db.models import Q
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _

from user.models import User


class DegreeTypes(models.TextChoices):
    OTHER = "other", _("Other")
    BACHELOR = "bachelor", _("Bachelor")
    MASTER = "master", _("Master")
    DOCTORATE = "doctorate", _("Doctorate")


class Classroom(models.Model):
    name = models.CharField(_("Name"), max_length=200)
    degree = models.CharField(_("Degree"), max_length=50, choices=DegreeTypes.choices, default=DegreeTypes.OTHER)
    course_code = models.CharField(_("Course code"), max_length=50, blank=True, null=True)
    teachers = models.ManyToManyField(
        User,
        related_name="lectures",
        verbose_name=_("Teachers"),
        limit_choices_to=Q(is_teacher=True) | Q(is_assistant=True),
    )
    students = models.ManyToManyField(User, related_name="enrollments", verbose_name=_("Students"))
    # timestamps
    updated_at = models.DateTimeField(_("Updated"), auto_now=True)
    created_at = models.DateTimeField(_("Created"), auto_now_add=True)

    @property
    def teacher_count(self) -> int:
        return self.teachers.count()

    @property
    def printable_teachers(self) -> str:
        return ", ".join([teacher.name_only for teacher in self.teachers.all()])

    @property
    def students_count(self) -> int:
        return self.students.count()

    @property
    def upcoming_exam(self):
        return self.exams.filter(end_time__gte=timezone.now()).order_by("start_time").first()

    def __str__(self) -> str:
        if self.course_code:
            return f"{self.name} ({self.course_code})"
        return self.name

    class Meta:
        verbose_name = _("Classroom")
        verbose_name_plural = _("Classrooms")
        ordering = ("-created_at",)

web/views/exam.py
"""
The exam page that will be used by students.
"""
from uuid import uuid4

from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.db import transaction
from django.http import Http404, HttpResponse, JsonResponse
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _
from django.views.generic import TemplateView, View

from exam.models import CodeEvaluationTracker, Exam, ExamQuestion, QuestionArtifact, QuestionTypes, Response
from exam.tasks import evaluate_user_response
from web.forms.question import CodeResponseForm


class ExamHomeView(LoginRequiredMixin, TemplateView):
    """List of questions for the selected exam."""

    template_name = "exam/index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["page_slug"] = "exams"
        exam_id = kwargs.get("exam_id")
        exam = (
            Exam.objects.filter(id=exam_id, classroom__students=self.request.user)
            .select_related("classroom")
            .prefetch_related("questions", "questions__question")
            .first()
        )
        if not exam:
            raise Http404(_("Exam does not exist!"))
        if not exam.is_open:
            raise PermissionDenied(_("Exam has not started yet!"))
        context["exam"] = exam
        return context


class QuestionView(LoginRequiredMixin, TemplateView):
    """Show question details and the response form."""

    template_name = "exam/question.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["page_slug"] = "exams"
        exam_id = kwargs.get("exam_id")
        question_id = kwargs.get("question_id")
        question = (
            ExamQuestion.objects.filter(id=question_id, exam__id=exam_id, exam__classroom__students=self.request.user)
            .select_related("question", "exam")
            .prefetch_related("exam__questions", "exam__questions__question")
            .first()
        )
        response = Response.objects.filter(student=self.request.user, exam_question=question).first()
        response_form = None
        if question.question.question_type == QuestionTypes.CODE:
            if response:
                response_form = CodeResponseForm(initial={"response": response.solution})
            elif question.question.test_template:
                response_form = CodeResponseForm(initial={"response": question.question.test_template})
            else:
                response_form = CodeResponseForm()
        context["exam"] = question.exam
        context["question"] = question
        context["question_types"] = QuestionTypes
        context["response"] = response
        context["response_form"] = response_form
        return context


class QuestionEvaluationView(LoginRequiredMixin, View):
    """Save the provided response and start the task if needed."""

    @staticmethod
    def get(request, *args, **kwargs):
        return JsonResponse({"status": "ready"}, safe=True, status=200)

    @staticmethod
    def post(request, *args, **kwargs):
        """Save a response to a question."""
        question_id = kwargs["question_id"]
        # get details for the question
        question = (
            ExamQuestion.objects.filter(id=question_id, exam__classroom__students=request.user)
            .select_related("exam", "question")
            .first()
        )
        if not question:
            return JsonResponse({"status": "error", "message": _("Question was not found!")}, safe=True, status=400)
        # check for the deadline
        if timezone.now() > question.exam.end_time:
            return JsonResponse(
                {"status": "error", "message": _("Submitting changes after the deadline is not allowed!")},
                safe=True,
                status=403,
            )
        solution = request.POST.get("solution")
        if not solution:
            return JsonResponse(
                {"status": "error", "message": _("The provided solution is empty.")}, safe=True, status=400
            )
        # make basic checks before storing the response
        if question.question.question_type == QuestionTypes.TEXT:
            if len(solution) > question.question.max_text_length:
                return JsonResponse(
                    {
                        "status": "error",
                        "message": _(f"Response cannot be longer than {question.question.max_text_length}."),
                    },
                    safe=True,
                    status=400,
                )
        elif question.question.question_type == QuestionTypes.CHOICE:
            if solution not in question.question.choices.keys():
                return JsonResponse(
                    {"status": "error", "message": _("The provided option is unknown.")}, safe=True, status=400
                )
        elif question.question.question_type == QuestionTypes.MULTI_CHOICE:
            if not all([sub_solution in question.question.choices.keys() for sub_solution in solution.split(",")]):
                return JsonResponse(
                    {"status": "error", "message": _("One of the provided options in unknown.")}, safe=True, status=400
                )
        elif question.question.question_type == QuestionTypes.CODE:
            # @TODO perform code safety checks
            pass
        # check if there is a response for this question
        response = Response.objects.filter(student=request.user, exam_question=question).first()
        if response:
            response.solution = solution
            response.total_score = 0
            response.score_details = {}
            response.save()
        else:
            response = Response.objects.create(student=request.user, exam_question=question, solution=solution)

        # Schedule a grading task
        task_id = None
        if question.in_exam_results:
            task_id = uuid4()
            CodeEvaluationTracker.objects.create(id=task_id, response=response)
            transaction.on_commit(
                lambda: evaluate_user_response.apply_async(kwargs={"response_id": response.id, "task_id": task_id})
            )

        # return response
        if question.question.question_type in [QuestionTypes.CHOICE, QuestionTypes.MULTI_CHOICE]:
            return JsonResponse({"status": "success", "message": _("Solution saved.")}, safe=True, status=200)
        elif question.question.question_type == QuestionTypes.CODE:
            if question.in_exam_results:
                return JsonResponse(
                    {"status": "success", "message": _("Code evaluation started..."), "task_id": task_id},
                    safe=True,
                    status=200,
                )
            return JsonResponse({"status": "success", "message": _("Solution saved.")}, safe=True, status=200)
        # text or anything else
        return JsonResponse({"status": "success", "message": _("Solution saved.")}, safe=True, status=200)

    @staticmethod
    def delete(request, *args, **kwargs):
        """Delete a response for a question."""
        question_id = kwargs["question_id"]
        # get details for the question
        question = (
            ExamQuestion.objects.filter(id=question_id, exam__classroom__students=request.user)
            .select_related("exam", "question")
            .first()
        )
        # check for the deadline
        if timezone.now() > question.exam.end_time:
            return JsonResponse(
                {"status": "error", "message": _("Submitting changes after the deadline is not allowed!")},
                safe=True,
                status=403,
            )
        if not question:
            return JsonResponse({"status": "error", "message": _("Question was not found!")}, safe=True, status=400)
        # check if there is a response for this question
        response = Response.objects.filter(student=request.user, exam_question=question).first()
        if not response:
            return JsonResponse({"status": "success", "message": _("Nothing to remove.")}, safe=True, status=200)
        response.delete()
        return JsonResponse({"status": "success", "message": _("Solution removed.")}, safe=True, status=200)


class EvaluationResultView(LoginRequiredMixin, View):
    @staticmethod
    def get(request, *args, **kwargs):
        evaluation_uuid = kwargs["evaluation_uuid"]
        tracker: CodeEvaluationTracker = (
            CodeEvaluationTracker.objects.filter(id=evaluation_uuid)
            .select_related("response", "response.exam_question")
            .first()
        )
        if not tracker:
            return JsonResponse({"status": "not_found", "message": _("Task was not found.")}, safe=True, status=404)
        if not tracker.ended_at:
            return JsonResponse(
                {"status": "waiting", "message": _("Task has not finished yet.")}, safe=True, status=202
            )
        # we have a result
        question_settings = tracker.response.exam_question
        show_results = question_settings.in_exam_results
        show_execution_warning = True
        execution_failed = False
        if "execution" in tracker.raw_results and tracker.raw_results["execution"] == "failed":
            execution_failed = True
        if execution_failed and show_execution_warning:
            return JsonResponse({"status": "completed", "message": _("Code failed")}, safe=True, status=400)
        # code did not fail
        if show_results:
            return JsonResponse(
                {"status": "completed", "message": _(f"Points: {tracker.response.total_score}")}, safe=True, status=200
            )
        return JsonResponse({"status": "completed", "message": _("Code was tested and saved.")}, safe=True, status=200)


class QuestionArtifactDownloadView(View):
    @staticmethod

web/templates/student/classrooms.html
{% extends "dashboard_base.html" %}
{% load i18n humanize %}
{% block page_title %}{% trans "Classrooms" %}{% endblock %}
{% block canonical_path %}dash/classrooms/{% endblock %}
{% block dashboard_content %}
<main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">{% trans "Classrooms" %}</h1>
    </div>
    <h2>{% trans "Enrolled classrooms" %}</h2>
    <div class="table-responsive">
        <table class="table table-striped table-sm">
            <thead>
            <tr>
                <th>#</th>
                <th>{% trans "Course" %}</th>
                <th>{% trans "Degree" %}</th>
                <th>{% trans "Teachers" %}</th>
                <th>{% trans "Students" %}</th>
                <th>{% trans "Upcoming exam" %}</th>
            </tr>
            </thead>
            <tbody>
            {% for classroom in classrooms %}
            <tr>
                <td><a href="{% url "web:exams_dashboard" %}?classroom={{ classroom.pk }}">{{ classroom.name }}</a></td>
                <td>{{ classroom.course_code }}</td>
                <td>{{ classroom.get_degree_display }}</td>
                <td>{{ classroom.printable_teachers }}</td>
                <td>{{ classroom.students_count }}</td>
                <td>
                    {% with classroom.upcoming_exam as upcoming_exam %}
                    {% if upcoming_exam %}{{ upcoming_exam.title }} ({{ upcoming_exam.start_time|naturaltime }}){% else %}-{% endif %}
                    {% endwith %}
                </td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</main>
{% endblock %}

web/templates/student/exams.html
{% extends "dashboard_base.html" %}
{% load i18n humanize %}
{% block page_title %}{% trans "Exams" %}{% endblock %}
{% block canonical_path %}dash/exams/{% endblock %}
{% block dashboard_content %}
    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
        <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <h1 class="h2">{% trans "Exams" %}</h1>
        </div>
        <h2>{% trans "Upcoming exams" %}{% if classroom %} (
            {{ classroom.name }}{% if classroom.course_code %} - {{ classroom.course_code }}){% endif %}{% endif %}</h2>
        <div class="table-responsive">
            <table class="table table-striped table-sm">
                <thead>
                <tr>
                    <th>{% trans "Exam" %}</th>
                    {% if not classroom %}
                        <th>{% trans "Classroom" %}</th>{% endif %}
                    <th>{% trans "Starts" %}</th>
                    <th>{% trans "Ends" %}</th>
                    <th>{% trans "Duration" %}</th>
                    <th>{% trans "Attend" %}</th>
                </tr>
                </thead>
                <tbody>
                {% for exam in exams %}
                    <tr>
                        <td>{{ exam.title }}</td>
                        {% if not classroom %}
                            <td>
                                <a href="{% url "web:classrooms" %}?classroom={{ exam.classroom.pk }}">{{ exam.classroom }}</a>
                            </td>{% endif %}
                        <td>{{ exam.start_time }}</td>
                        <td>{{ exam.end_time }}</td>
                        <td>
                            {% blocktrans with duration=exam.duration_in_minutes %}
                                {{ duration }} minutes
                            {% endblocktrans %}
                        </td>
                        <td>
                            {% if exam.is_open %}
                                <a href="{% url "web:exam_page" exam_id=exam.id %}">{% trans "Start" %}</a>
                            {% else %}
                                {% trans "Not started" %}
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </main>
{% endblock %}

web/templates/student/index.html
{% extends "dashboard_base.html" %}
{% load i18n humanize %}
{% block page_title %}{% trans "Student Dashboard" %}{% endblock %}
{% block canonical_path %}dash/{% endblock %}
{% block dashboard_content %}
<main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">{% trans "Dashboard" %}</h1>
    </div>
</main>
{% endblock %}