dems/urls.py
from django.contrib import admin
from django.urls import include, path
from django.utils.translation import ugettext_lazy as _

urlpatterns = [
    path("admin/", admin.site.urls),
    path("markdownx/", include("markdownx.urls")),
    path("", include(("web.urls", "web"), namespace="web")),
]


admin.site.site_header = _("DEMS Admin")
admin.site.site_title = _("DEMS Admin")
admin.site.index_title = _("Welcome to the Digital Exam Management System")

web/urls.py
from django.urls import path

from web.views.dashboard import StudentClassroomsView, StudentDashboardView, StudentExamsView
from web.views.exam import ExamHomeView, QuestionArtifactDownloadView, QuestionEvaluationView, QuestionView
from web.views.main import HomepageView, LoginView, logout_view

urlpatterns = [
    path("", HomepageView.as_view(), name="homepage"),
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", logout_view, name="logout"),
    path("dash/classrooms/", StudentClassroomsView.as_view(), name="classrooms"),
    path(
        "dash/exams/<int:exam_id>/<int:question_id>/evaluate/",
        QuestionEvaluationView.as_view(),
        name="question_evaluation_ajax",
    ),
    path("dash/exams/<int:exam_id>/<int:question_id>/", QuestionView.as_view(), name="question_page"),
    path("dash/exams/<int:exam_id>/", ExamHomeView.as_view(), name="exam_page"),
    path("dash/exams/", StudentExamsView.as_view(), name="exams_dashboard"),
    path("dash/", StudentDashboardView.as_view(), name="student_dashboard"),
    path(
        "download/<int:question_id>/<uuid:artifact_uuid>/",
        QuestionArtifactDownloadView.as_view(),
        name="artifact_download",
    ),
]

web/templates/base.html
<!doctype html>
{% load i18n static %}{% get_current_language as LANGUAGE_CODE %}
<html lang="{{ LANGUAGE_CODE }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="{% trans "Digital Exam Management System - Manage your coding exams online." %}">
    <meta name="keywords" content="digital, exam, coding, manage, online, python">
    <meta name="author" content="Emin Mastizada">
    <title>{% block page_title %}{% endblock %} - DEMS</title>
    {% block canonical_url %}
        <link rel="canonical" href="https://dems.debugwith.me/{% block canonical_path %}{% endblock %}">{% endblock %}
    <!-- Bootstrap core CSS -->
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
    <link href="{% static "css/extra.css" %}" rel="stylesheet">
    {% block extra_css %}{% endblock %}

    <!-- Favicons -->
    {#    <link rel="apple-touch-icon" href="/docs/5.0/assets/img/favicons/apple-touch-icon.png" sizes="180x180">#}
    {#    <link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">#}
    {#    <link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">#}
    {#    <link rel="manifest" href="/docs/5.0/assets/img/favicons/manifest.json">#}
    {#    <link rel="mask-icon" href="/docs/5.0/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">#}
    {#    <link rel="icon" href="/docs/5.0/assets/img/favicons/favicon.ico">#}
    {#    <meta name="theme-color" content="#7952b3">#}

</head>
<body>
{% block header %}
    <header class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
        <p class="h5 my-0 me-md-auto fw-normal" title="{% trans "Digital Exam Management System" %}">DEMS</p>
        {% if request.user.is_authenticated %}
            <a class="nav-link dropdown-toggle" href="#" id="userDropdownToggle" data-bs-toggle="dropdown"
               aria-expanded="false">{{ request.user }}</a>
            <ul class="dropdown-menu" aria-labelledby="userDropdownToggle">
                <li><a class="dropdown-item" href="{% url "web:student_dashboard" %}">{% trans "Dashboard" %}</a></li>
                <li><a class="dropdown-item" href="{% url "web:classrooms" %}">{% trans "Classrooms" %}</a></li>
                <li><a class="dropdown-item" href="#">{% trans "Scores" %}</a></li>
            </ul>
        {% else %}
            <a class="btn btn-outline-primary" href="{% url "web:login" %}">{% trans "Login" %}</a>
        {% endif %}
    </header>
{% endblock %}
{% block entire_block %}
    <main class="container">
        {% block container %}{% endblock %}
        {% block footer %}
            <footer class="pt-4 my-md-5 pt-md-5 border-top">
                <div class="row">
                    <div class="col-12 col-md">
                        <img class="mb-2" src="logo" alt="" width="24" height="19">
                        <small class="d-block mb-3 text-muted">&copy; 2021 DEMS</small>
                    </div>
                    <div class="col-6 col-md">

                    </div>
                    <div class="col-6 col-md">

                    </div>
                    <div class="col-6 col-md">
                        <h5>{% trans "About" %}</h5>
                        <ul class="list-unstyled text-small">
                            <li><a class="link-secondary" href="#">{% trans "Source code" %}</a> <i
                                    class="fab fa-gitlab"></i></li>
                            <li><a class="link-secondary" href="#">{% trans "About" %}</a> <i class="fas fa-info"></i>
                            </li>
                            <li><a class="link-secondary" href="#">{% trans "Terms & Privacy" %}</a> <i
                                    class="fas fa-file-contract"></i></li>
                        </ul>
                    </div>
                </div>
            </footer>
        {% endblock %}
    </main>
{% endblock %}
<script type="text/javascript" src="{% static "js/jquery.min.js" %}"></script>
<script type="text/javascript" src="{% static "js/bootstrap.bundle.min.js" %}"></script>
<script type="text/javascript" src="{% static "js/fontawesome.all.min.js" %}"></script>
{% block extra_js %}{% endblock %}
</body>
</html>

web/templates/dashboard_base.html
{% extends "base.html" %}
{% load i18n static %}
{% block extra_css %}
    <link href="{% static "css/dashboard.css" %}" rel="stylesheet">
    {% block dashboard_css %}{% endblock %}
{% endblock %}

{% block header %}
    <header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
        <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="#">DEMS</a>
        <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse"
                data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false"
                aria-label="{% trans "Toggle navigation" %}">
            <span class="navbar-toggler-icon"></span>
        </button>
        <input class="form-control form-control-dark w-100" type="text" placeholder="{% trans "Search" %}"
               aria-label="{% trans "Search" %}">
        <ul class="navbar-nav px-3">
            <li class="nav-item text-nowrap">
                <a class="nav-link" href="{% url "web:logout" %}">{% trans "Sign out" %}</a>
            </li>
        </ul>
    </header>
{% endblock %}
{% block entire_block %}
    <div class="container-fluid">
        <div class="row">
            <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
                <div class="position-sticky pt-3">
                    <ul class="nav flex-column">
                        <li class="nav-item">
                            <a class="nav-link{% if not page_slug or page_slug == "dashindex"%} active{% endif %}" aria-current="page" href="{% url "web:student_dashboard" %}">
                                <i class="fas fa-home"></i>
                                {% trans "Dashboard" %}
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link{% if page_slug == "classrooms" %} active{% endif %}" href="{% url "web:classrooms" %}">
                                <i class="fas fa-university"></i>
                                {% trans "Classrooms" %}
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link{% if page_slug == "scores" %} active{% endif %}" href="#">
                                <i class="fas fa-star-half-alt"></i>
                                {% trans "Scores" %}
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link{% if page_slug == "exams" %} active{% endif %}" href="{% url "web:exams_dashboard" %}">
                                <i class="fas fa-laptop-code"></i>
                                {% trans "Exams" %}
                            </a>
                        </li>
                    </ul>
                    {% block extra_dash_sidebar %}{% endblock %}
                </div>
            </nav>
            {% block dashboard_content %}{% endblock %}
        </div>
    </div>
{% endblock %}

web/templates/index.html
{% extends "base.html" %}
{% load i18n %}
{% block page_title %}{% trans "Homepage" %}{% endblock %}
{% block container %}
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">{% trans "Digital Exam Management System" %}</h1>
        <p class="lead">{% trans "Manage your coding exams online." %}</p>
    </div>

    <div class="row row-cols-1 row-cols-md-2 homepage-function-list text-center">
        <div class="col">
            <div class="card mb-4 shadow-sm">
                <div class="card-header">
                    <h4 class="my-0 fw-normal">{% trans "Students" %}</h4>
                </div>
                <div class="card-body">
                    <ul class="list-unstyled mt-3 mb-4">
                        <li>{% trans "Online code testing" %}</li>
                        <li>{% trans "Quick exam results" %}</li>
                        <li>{% trans "Syntax checking" %}</li>
                    </ul>
                    <a href="{% url "web:login" %}" type="button"
                       class="w-100 btn btn-lg btn-outline-primary">{% trans "Login" %}</a>
                </div>
            </div>
        </div>
        <div class="col">
            <div class="card mb-4 shadow-sm">
                <div class="card-header">
                    <h4 class="my-0 fw-normal">{% trans "Teachers" %}</h4>
                </div>
                <div class="card-body">
                    <ul class="list-unstyled mt-3 mb-4">
                        <li>{% trans "Host online exams" %}</li>
                        <li>{% trans "Automatic grading" %}</li>
                        <li>{% trans "Import/Export" %}</li>
                    </ul>
                    <button type="button" class="w-100 btn btn-lg btn-primary disabled"
                            disabled>{% trans "Contact the department" %}</button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}