dems/urls.py
from django.contrib import admin
from django.urls import include, path
from django.utils.translation import ugettext_lazy as _

urlpatterns = [
    path("admin/", admin.site.urls),
    path("markdownx/", include("markdownx.urls")),
    path("", include(("web.urls", "web"), namespace="web")),
]


admin.site.site_header = _("DEMS Admin")
admin.site.site_title = _("DEMS Admin")
admin.site.index_title = _("Welcome to the Digital Exam Management System")

web/urls.py
from django.urls import path

from web.views.dashboard import StudentClassroomsView, StudentDashboardView, StudentExamsView
from web.views.exam import ExamHomeView, QuestionArtifactDownloadView, QuestionEvaluationView, QuestionView
from web.views.main import HomepageView, LoginView, logout_view

urlpatterns = [
    path("", HomepageView.as_view(), name="homepage"),
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", logout_view, name="logout"),
    path("dash/classrooms/", StudentClassroomsView.as_view(), name="classrooms"),
    path(
        "dash/exams/<int:exam_id>/<int:question_id>/evaluate/",
        QuestionEvaluationView.as_view(),
        name="question_evaluation_ajax",
    ),
    path("dash/exams/<int:exam_id>/<int:question_id>/", QuestionView.as_view(), name="question_page"),
    path("dash/exams/<int:exam_id>/", ExamHomeView.as_view(), name="exam_page"),
    path("dash/exams/", StudentExamsView.as_view(), name="exams_dashboard"),
    path("dash/", StudentDashboardView.as_view(), name="student_dashboard"),
    path(
        "download/<int:question_id>/<uuid:artifact_uuid>/",
        QuestionArtifactDownloadView.as_view(),
        name="artifact_download",
    ),
]

exam/models.py
import os
from typing import List
from uuid import uuid4

from django.db import models
from django.db.models import UniqueConstraint
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _
from markdownx.models import MarkdownxField

from classroom.models import Classroom
from user.models import User


class QuestionTypes(models.IntegerChoices):
    CHOICE = 1, _("Checkbox")
    MULTI_CHOICE = 2, _("Multiple choice")
    TEXT = 3, _("Text answer")
    CODE = 4, _("Coding")


def question_artifact_path(instance, filename):
    return f"questions/{instance.question.id}/{filename}"


class Question(models.Model):
    """Question details."""

    internal_title = models.CharField(
        _("Internal title"), max_length=200, help_text=_("Internal title is only shown to teachers and assistants.")
    )
    title = models.CharField(_("Title"), max_length=200, help_text=_("Headline of the question."))
    description = MarkdownxField(_("Description"), help_text=_("Description for the question. Use markdown syntax."))
    question_type = models.IntegerField(
        _("Question type"), choices=QuestionTypes.choices, default=QuestionTypes.CHOICE
    )
    # checkbox and multi-choice question properties
    correct_choice = models.CharField(
        _("Correct choice indexes"),
        help_text=_("Correct choice indexes separated by comma"),
        max_length=50,
        blank=True,
        null=True,
    )
    choices = models.JSONField(
        _("Choices"), default=dict, blank=True, help_text=_("JSON with key, value for checkbox options")
    )
    # text question properties
    max_text_length = models.IntegerField(
        _("Max response length"), default=255, help_text=_("Maximum length of the text question response.")
    )
    # coding question properties
    example_solution = models.TextField(
        _("Example solution"), blank=True, null=True, help_text=_("Example solution to verify test cases.")
    )
    test_cases = models.TextField(
        _("Test cases"),
        blank=True,
        null=True,
        help_text=_("Pytest style testing cases. Import user functions from the user_code module."),
    )
    test_template = models.TextField(
        _("Test template"), blank=True, null=True, help_text=_("Template that will be provided to students.")
    )
    # control notes
    allow_notes = models.BooleanField(
        _("Allow notes"), default=False, help_text=_("Allow students to add custom notes.")
    )
    # question author
    author = models.ForeignKey(
        User, related_name="questions", on_delete=models.SET_NULL, null=True, verbose_name=_("Author")
    )
    # timestamps
    updated_at = models.DateTimeField(_("Updated"), auto_now=True)
    created_at = models.DateTimeField(_("Created"), auto_now_add=True)

    def __str__(self) -> str:
        return self.title

    class Meta:
        verbose_name = _("Question")
        verbose_name_plural = _("Questions")
        ordering = ("-updated_at",)


class QuestionArtifact(models.Model):
    """
    Additional files required by the question.
    This is used for the coding questions where extra files (like txt) are required for test cases.
    """

    id = models.UUIDField(_("UUID"), primary_key=True, default=uuid4, editable=False)
    question = models.ForeignKey(
        Question, related_name="artifacts", on_delete=models.CASCADE, verbose_name=_("Question")
    )
    file = models.FileField(
        _("File"),
        upload_to=question_artifact_path,
        help_text=_("Files will be mounted to the test environment with the user and test codes."),
    )
    # timestamps
    updated_at = models.DateTimeField(_("Updated"), auto_now=True)

    def __str__(self) -> str:
        return str(self.id)

    @property
    def filename(self) -> str:
        return os.path.basename(self.file.name)

    class Meta:
        verbose_name = _("Artifact")
        verbose_name_plural = _("Artifacts")
        ordering = ("updated_at",)


class Exam(models.Model):
    """Exam details."""

    title = models.CharField(_("Title"), max_length=200, help_text=_("Headline of the exam."))
    classroom = models.ForeignKey(
        Classroom,
        related_name="exams",
        on_delete=models.CASCADE,
        verbose_name=_("Classroom"),
        help_text=_("Exams can only be attended by students in this classroom."),
    )
    start_time = models.DateTimeField(_("Starts at"), help_text=_("When exam will be open for students."))
    end_time = models.DateTimeField(_("Ends at"), help_text=_("Responses after the deadline will not be accepted."))
    # timestamps
    updated_at = models.DateTimeField(_("Updated"), auto_now=True)
    created_at = models.DateTimeField(_("Created"), auto_now_add=True)

    @property
    def duration(self) -> int:
        """Exam duration in seconds."""
        return (self.end_time - self.start_time).seconds

    @property
    def duration_in_minutes(self) -> int:
        """Exam duration in minutes."""
        return int(self.duration / 60 + 0.5)

    @property
    def is_open(self) -> bool:
        """Can exam be attended now?"""
        now = timezone.now()
        return self.end_time > now > self.start_time

    def __str__(self) -> str:
        return self.title

    class Meta:
        verbose_name = _("Exam")
        verbose_name_plural = _("Exams")
        ordering = ("-updated_at",)


class ExamQuestion(models.Model):
    """M2M relation between Exams and Questions with extra details like points."""

    exam = models.ForeignKey(Exam, related_name="questions", on_delete=models.CASCADE, verbose_name=_("Exam"))
    question = models.ForeignKey(Question, related_name="exams", on_delete=models.CASCADE, verbose_name=_("Questions"))
    rank = models.IntegerField(_("Rank"), default=5, help_text=_("Ranks are used to order questions in the exam."))
    points = models.FloatField(_("Points"), default=10, help_text=_("Maximum points of the question."))
    syntax_penalty = models.FloatField(
        _("Max syntax penalty"), default=2, help_text=_("Maximum code syntax penalty, used for CODING questions.")
    )
    test_case_points = models.JSONField(
        _("Test case scores"),
        default=dict,
        blank=True,
        help_text=_(
            "You can provide custom score for each test case."
            "Use the name of the test case as the key, and points for that case as the value."
        ),
    )
    in_exam_results = models.BooleanField(
        _("Results during exam"), default=True, help_text=_("Show evaluation results of the answer during the exam.")
    )
    # timestamps
    created_at = models.DateTimeField(_("Created"), auto_now_add=True)

    def __str__(self) -> str:
        return str(self.pk)

    class Meta:
        verbose_name = _("Exam question")
        verbose_name_plural = _("Exam questions")
        ordering = ("exam", "rank", "id")


class Response(models.Model):
    """Response for the exam question."""

    student = models.ForeignKey(User, related_name="responses", on_delete=models.CASCADE, verbose_name=_("Student"))
    exam_question = models.ForeignKey(
        ExamQuestion, related_name="responses", on_delete=models.CASCADE, verbose_name=_("Exam question")
    )
    solution = models.TextField(_("Solution"), blank=True, null=True)
    notes = models.TextField(_("Notes"), blank=True, null=True)
    # results
    total_score = models.FloatField(
        _("Total score"), blank=True, null=True, help_text=_("Score earned for this solution.")
    )
    score_details = models.JSONField(
        _("Score details"), default=dict, blank=True, help_text=_("Details provided by the auto grading system.")
    )
    # timestamps
    updated_at = models.DateTimeField(_("Updated"), auto_now=True)
    created_at = models.DateTimeField(_("Created"), auto_now_add=True)

    def __str__(self) -> str:
        return str(self.pk)

    @property
    def splitted_solution(self) -> List[str]:
        if not self.solution:
            return []
        return self.solution.split(",")

    class Meta:
        verbose_name = _("Response")
        verbose_name_plural = _("Responses")
        ordering = ("student__id", "-updated_at")
        constraints = [UniqueConstraint(name="unique_student_response", fields=["student", "exam_question"])]


class CodeEvaluationTracker(models.Model):
    id = models.UUIDField(_("Task id"), primary_key=True, default=uuid4, editable=False)
    response = models.ForeignKey(
        Response, related_name="code_evaluations", verbose_name=_("Response"), on_delete=models.CASCADE
    )
    raw_results = models.JSONField(
        _("Raw results"), default=dict, blank=True, help_text=_("Raw output of the evaluation.")
    )
    started_at = models.DateTimeField(_("Started"), blank=True, null=True)
    ended_at = models.DateTimeField(_("Ended"), blank=True, null=True)
    created_at = models.DateTimeField(_("Created"), auto_now_add=True)

    def __str__(self) -> str:
        return str(self.id)

    class Meta:
        verbose_name = _("Code evaluation tracker")
        verbose_name_plural = _("Code evaluation trackers")
        ordering = ("-created_at",)

web/forms/question.py
from django import forms
from django_ace import AceWidget


class CodeResponseForm(forms.Form):
    response = forms.CharField(widget=AceWidget(theme="dracula", mode="python"))

web/templates/exam/_choice_question.html
{% load i18n %}
<form>
    {% csrf_token %}
{% for option, value in question.question.choices.items %}
    <div class="form-check">
        <input class="form-check-input" type="radio" name="solution" id="response_choice{{ forloop.counter }}" value="{{ option }}"{% if response and option == response.solution %} checked{% endif %}>
        <label class="form-check-label" for="response_choice{{ forloop.counter }}">{{ value }}</label>
    </div>
{% endfor %}
</form>

web/templates/exam/_code_question.html
{% load i18n %}
<form>
    {% csrf_token %}
{{ response_form.response }}
{{ response_form.media }}
</form>

web/templates/exam/_multi_choice_question.html
{% load i18n %}
<form>
    {% csrf_token %}
{% for option, value in question.question.choices.items %}
    <div class="form-check">
        <input class="form-check-input" type="checkbox" name="solution" id="response_mchoice{{ forloop.counter }}" value="{{ option }}"{% if response and option in response.splitted_solution %} checked{% endif %}>
        <label class="form-check-label" for="response_mchoice{{ forloop.counter }}">{{ value }}</label>
    </div>
{% endfor %}
</form>

web/templates/exam/_text_question.html
{% load i18n %}
<form>
    {% csrf_token %}
<label class="visually-hidden" for="response_text">{% trans "Response" %}</label>
<textarea maxlength="{{ question.question.max_text_length }}" id="response_text" name="solution"
          placeholder="{% trans "Provide your answer here." %}" rows="7" class="response-text-area">{% if response %}{{ response.solution }}{% endif %}</textarea>
</form>

web/templates/exam/index.html
{% extends "dashboard_base.html" %}
{% load i18n humanize dashtags %}
{% block page_title %}{{ exam.title }}{% endblock %}
{% block canonical_path %}dash/exams/{{ exam.pk }}/{% endblock %}
{% block extra_dash_sidebar %}
<h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
  <span>{% trans "Questions" %}</span>
</h6>
<ol class="nav flex-column mb-2 question-nav-list">
    {% for question in exam.questions.all %}
    <li class="nav-item">
        <a class="nav-link" href="{% url "web:question_page" exam.id question.id %}">
            {{ question.question.title }} ({% blocktrans with points=question.points %}{{ points }} points{% endblocktrans %})
        </a>
    </li>
    {% endfor %}
</ol>
{% endblock %}
{% block dashboard_content %}
<main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">{{ exam.title }}</h1>
    </div>
    <h2>{% trans "Questions" %}</h2>
    <div class="table-responsive">
        <table class="table table-striped table-sm">
            <thead>
            <tr>
                <th>{% trans "Question" %}</th>
                <th>{% trans "Type" %}</th>
                <th>{% trans "Points" %}</th>
                <th>{% trans "Answered" %}</th>
            </tr>
            </thead>
            <tbody>
            {% for question in exam.questions.all %}
            <tr>
                <td><a href="{% url "web:question_page" exam.id question.id %}">{{ question.question.title }}</a></td>
                <td>{{ question.question.get_question_type_display }}</td>
                <td>{{ question.points }}</td>
                <td>
                    {% with request.user|question_response:question as response %}
                        {% if response %}
                            <i class="fas fa-check-circle color-green"></i>
                        {% else %}
                            <i class="fas fa-times-circle color-red"></i>
                        {% endif %}
                    {% endwith %}
                </td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</main>
{% endblock %}

web/templates/exam/question.html
{% extends "dashboard_base.html" %}
{% load i18n static humanize dashtags %}
{% block page_title %}{{ question.question.title }}{% endblock %}
{% block canonical_path %}dash/exams/{{ exam.pk }}/{{ question.pk }}/{% endblock %}
{% block extra_dash_sidebar %}
<h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
  <span>{% trans "Questions" %}</span>
</h6>
<ol class="nav flex-column mb-2 question-nav-list">
    {% for question in exam.questions.all %}
    <li class="nav-item">
        <a class="nav-link" href="{% url "web:question_page" exam.id question.id %}">
            {{ question.question.title }} ({% blocktrans with points=question.points %}{{ points }} points{% endblocktrans %})
        </a>
    </li>
    {% endfor %}
</ol>
{% endblock %}
{% block dashboard_content %}
<main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">{{ question.question.title }}</h1>
    </div>
    <h3>
        {{ question.question.description|markdown_to_html|safe }}
    </h3>
    {% if question.question.question_type == question_types.TEXT %}
        {% include "exam/_text_question.html" with exam=exam question=question response=response %}
    {% elif question.question.question_type == question_types.CHOICE %}
        {% include "exam/_choice_question.html" with exam=exam question=question response=response %}
    {% elif question.question.question_type == question_types.MULTI_CHOICE %}
        {% include "exam/_multi_choice_question.html" with exam=exam question=question response=response %}
    {% elif question.question.question_type == question_types.CODE %}
        {% include "exam/_code_question.html" with exam=exam question=question response_form=response_form response=response %}
    {% else %}
        <span class="color-red">
            {% blocktrans with question_type=question.question.get_question_type_display %}Unknown question type: {{ question_type }}{% endblocktrans %}
        </span>
    {% endif %}
    <div class="clear">&nbsp;</div>
    <div class="ajax-results">
        <span class="result-span"></span>
    </div>
    <div class="clear">&nbsp;</div>
    <div class="save-results">
        <button class="btn btn-success submit-response-button" title="{% trans "Save a response for this question." %}">{% trans "Submit" %}</button>
        <a href="{% url "web:exam_page" exam.id %}" class="btn btn-secondary"><i class="fas fa-step-backward"></i> {% trans "Return" %}</a>
        <button class="btn btn-danger remove-response-button" title="{% trans "Remove the response for this question." %}">{% trans "Remove" %}</button>
    </div>
</main>
{% endblock %}
{% block extra_js %}
    <!--suppress UnreachableCodeJS, JSJQueryEfficiency -->
    <script>
        function getCookie(name) {
            let cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                let cookies = document.cookie.split(';');
                for (let i = 0; i < cookies.length; i++) {
                    let cookie = jQuery.trim(cookies[i]);
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }

        let csrftoken = getCookie('csrftoken');

        function csrfSafeMethod(method) {
            // these HTTP methods do not require CSRF protection
            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        }

        $.ajaxSetup({
            beforeSend: function (xhr, settings) {
                if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                    xhr.setRequestHeader("X-CSRFToken", csrftoken);
                }
            }
        });

        function get_solution() {
            {% if question.question.question_type == question_types.TEXT %}
                return $("#response_text").val();
            {% elif question.question.question_type == question_types.CODE %}
                return $("#id_response").val();
            {% elif question.question.question_type == question_types.CHOICE %}
                return $("input[name='solution']:checked").val();
            {% elif question.question.question_type == question_types.MULTI_CHOICE %}
                let responses = [];
                $.each($("input[name='solution']:checked"), function(){
                    responses.push($(this).val());
                });
                return responses.join(",");
            {% endif %}
        }

        $(document).ready(function() {
            let submit_button = $(".submit-response-button");
            let remove_button = $(".remove-response-button");
            let result_box = $(".result-span");
            submit_button.on("click", function(e) {
                e.preventDefault();
                submit_button.prop("disabled", true);
                result_box.removeClass("color-red");
                result_box.removeClass("color-green");
                let response = get_solution();
                if (typeof response === "undefined") {
                    result_box.text("{% trans "Please, select one of the listed options." %}");
                    result_box.addClass("color-red");
                    submit_button.prop("disabled", false);
                    return;
                }
                $.ajax({
                    url: "{% url "web:question_evaluation_ajax" exam.pk question.pk %}",
                    type: "POST",
                    data: {
                        solution: response
                    },
                    success: function (data) {
                        result_box.text(data.message);
                        result_box.addClass("color-green");
                    },
                    error: function (xhr) {
                        let data = JSON.parse(xhr.responseText);
                        result_box.text(data.message);
                        result_box.addClass("color-red");
                    },
                });
                submit_button.prop("disabled", false);
            });
            remove_button.on("click", function (e) {
                e.preventDefault();
                remove_button.prop("disabled", true);
                result_box.removeClass("color-red");
                result_box.removeClass("color-green");
                $.ajax({
                    url: "{% url "web:question_evaluation_ajax" exam.pk question.pk %}",
                    type: "DELETE",
                    data: {},
                    success: function (data) {
                        result_box.text(data.message);
                        result_box.addClass("color-green");
                    },
                    error: function (xhr) {
                        let data = JSON.parse(xhr.responseText);
                        result_box.text(data.message);
                        result_box.addClass("color-red");
                    },
                });
                remove_button.prop("disabled", false);
            });
        });

    </script>
{% endblock %}